//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class Allergy {
    
    private System.DateTime dateDiagnosedField;
    
    private bool dateDiagnosedFieldSpecified;
    
    private string diagnosedByField;
    
    private AllergyAllergen allergenField;
    
    private string reactionField;
    
    private string specificsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dateDiagnosed {
        get {
            return this.dateDiagnosedField;
        }
        set {
            this.dateDiagnosedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateDiagnosedSpecified {
        get {
            return this.dateDiagnosedFieldSpecified;
        }
        set {
            this.dateDiagnosedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string diagnosedBy {
        get {
            return this.diagnosedByField;
        }
        set {
            this.diagnosedByField = value;
        }
    }
    
    /// <remarks/>
    public AllergyAllergen allergen {
        get {
            return this.allergenField;
        }
        set {
            this.allergenField = value;
        }
    }
    
    /// <remarks/>
    public string reaction {
        get {
            return this.reactionField;
        }
        set {
            this.reactionField = value;
        }
    }
    
    /// <remarks/>
    public string specifics {
        get {
            return this.specificsField;
        }
        set {
            this.specificsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class AllergyAllergen {
    
    private CodedValue typeField;
    
    private CodedValue nameField;
    
    /// <remarks/>
    public CodedValue type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
