//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class Demographics {
    
    private System.DateTime dateOfBirthField;
    
    private bool dateOfBirthFieldSpecified;
    
    private System.DateTime dateOfDeathField;
    
    private bool dateOfDeathFieldSpecified;
    
    private string genderField;
    
    private string[] ethnicityField;
    
    private string[] languageField;
    
    private string maritalStatusField;
    
    private string employmentStatusField;
    
    private string employmentIndustryField;
    
    private string occupationField;
    
    private string religionField;
    
    private string incomeField;
    
    private string highestEducationField;
    
    private bool organDonorField;
    
    private bool organDonorFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dateOfBirth {
        get {
            return this.dateOfBirthField;
        }
        set {
            this.dateOfBirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateOfBirthSpecified {
        get {
            return this.dateOfBirthFieldSpecified;
        }
        set {
            this.dateOfBirthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dateOfDeath {
        get {
            return this.dateOfDeathField;
        }
        set {
            this.dateOfDeathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateOfDeathSpecified {
        get {
            return this.dateOfDeathFieldSpecified;
        }
        set {
            this.dateOfDeathFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ethnicity")]
    public string[] ethnicity {
        get {
            return this.ethnicityField;
        }
        set {
            this.ethnicityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("language")]
    public string[] language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string maritalStatus {
        get {
            return this.maritalStatusField;
        }
        set {
            this.maritalStatusField = value;
        }
    }
    
    /// <remarks/>
    public string employmentStatus {
        get {
            return this.employmentStatusField;
        }
        set {
            this.employmentStatusField = value;
        }
    }
    
    /// <remarks/>
    public string employmentIndustry {
        get {
            return this.employmentIndustryField;
        }
        set {
            this.employmentIndustryField = value;
        }
    }
    
    /// <remarks/>
    public string occupation {
        get {
            return this.occupationField;
        }
        set {
            this.occupationField = value;
        }
    }
    
    /// <remarks/>
    public string religion {
        get {
            return this.religionField;
        }
        set {
            this.religionField = value;
        }
    }
    
    /// <remarks/>
    public string income {
        get {
            return this.incomeField;
        }
        set {
            this.incomeField = value;
        }
    }
    
    /// <remarks/>
    public string highestEducation {
        get {
            return this.highestEducationField;
        }
        set {
            this.highestEducationField = value;
        }
    }
    
    /// <remarks/>
    public bool organDonor {
        get {
            return this.organDonorField;
        }
        set {
            this.organDonorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool organDonorSpecified {
        get {
            return this.organDonorFieldSpecified;
        }
        set {
            this.organDonorFieldSpecified = value;
        }
    }
}
