//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class ExercisePlan {
    public ExercisePlan()
	{
		exerciseGroupsField = new List<ExercisePlanExerciseGroup>();
	}
	
    private List<ExercisePlanExerciseGroup> exerciseGroupsField;
    
    /// <remarks/>
    public List<ExercisePlanExerciseGroup> exerciseGroups {
        get {
            return this.exerciseGroupsField;
        }
        set {
            this.exerciseGroupsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroup {
    public ExercisePlanExerciseGroup()
	{
		setsField = new ExercisePlanExerciseGroupSets();
		exercisesField = new List<ExercisePlanExerciseGroupExercise>();
	}
	
    private ExercisePlanExerciseGroupSets setsField;
    
    private string daysOfWeekField;
    
    private List<ExercisePlanExerciseGroupExercise> exercisesField;
    
    /// <remarks/>
    public ExercisePlanExerciseGroupSets sets {
        get {
            return this.setsField;
        }
        set {
            this.setsField = value;
        }
    }
    
    /// <remarks/>
    public string daysOfWeek {
        get {
            return this.daysOfWeekField;
        }
        set {
            this.daysOfWeekField = value;
        }
    }
    
    /// <remarks/>
    public List<ExercisePlanExerciseGroupExercise> exercises {
        get {
            return this.exercisesField;
        }
        set {
            this.exercisesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupSets {
    
    private int minimumValueField;
    
    private int maximumValueField;
    
    private bool maximumValueFieldSpecified;
    
    /// <remarks/>
    public int minimumValue {
        get {
            return this.minimumValueField;
        }
        set {
            this.minimumValueField = value;
        }
    }
    
    /// <remarks/>
    public int maximumValue {
        get {
            return this.maximumValueField;
        }
        set {
            this.maximumValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumValueSpecified {
        get {
            return this.maximumValueFieldSpecified;
        }
        set {
            this.maximumValueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExercise {
    public ExercisePlanExerciseGroupExercise()
	{
		activityField = new ExercisePlanExerciseGroupExerciseActivity();
		setsField = new ExercisePlanExerciseGroupExerciseSets();
		repititionsField = new ExercisePlanExerciseGroupExerciseRepititions();
		resistanceField = new ExercisePlanExerciseGroupExerciseResistance();
		distanceField = new ExercisePlanExerciseGroupExerciseDistance();
		additionalDetailsField = new ExercisePlanExerciseGroupExerciseAdditionalDetails();
	}
	
    private ExercisePlanExerciseGroupExerciseActivity activityField;
    
    private string orderedByField;
    
    private System.DateTime orderDateField;
    
    private bool orderDateFieldSpecified;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private int durationField;
    
    private bool durationFieldSpecified;
    
    private ExercisePlanExerciseGroupExerciseSets setsField;
    
    private ExercisePlanExerciseGroupExerciseRepititions repititionsField;
    
    private ExercisePlanExerciseGroupExerciseResistance resistanceField;
    
    private ExercisePlanExerciseGroupExerciseDistance distanceField;
    
    private ExercisePlanExerciseGroupExerciseAdditionalDetails additionalDetailsField;
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseActivity activity {
        get {
            return this.activityField;
        }
        set {
            this.activityField = value;
        }
    }
    
    /// <remarks/>
    public string orderedBy {
        get {
            return this.orderedByField;
        }
        set {
            this.orderedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime orderDate {
        get {
            return this.orderDateField;
        }
        set {
            this.orderDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderDateSpecified {
        get {
            return this.orderDateFieldSpecified;
        }
        set {
            this.orderDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool durationSpecified {
        get {
            return this.durationFieldSpecified;
        }
        set {
            this.durationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseSets sets {
        get {
            return this.setsField;
        }
        set {
            this.setsField = value;
        }
    }
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseRepititions repititions {
        get {
            return this.repititionsField;
        }
        set {
            this.repititionsField = value;
        }
    }
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseResistance resistance {
        get {
            return this.resistanceField;
        }
        set {
            this.resistanceField = value;
        }
    }
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseDistance distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseAdditionalDetails additionalDetails {
        get {
            return this.additionalDetailsField;
        }
        set {
            this.additionalDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseActivity {
    
    private string idField;
    
    private string typeField;
    
    private string nameField;
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseSets {
    
    private int minimumValueField;
    
    private int maximumValueField;
    
    private bool maximumValueFieldSpecified;
    
    /// <remarks/>
    public int minimumValue {
        get {
            return this.minimumValueField;
        }
        set {
            this.minimumValueField = value;
        }
    }
    
    /// <remarks/>
    public int maximumValue {
        get {
            return this.maximumValueField;
        }
        set {
            this.maximumValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumValueSpecified {
        get {
            return this.maximumValueFieldSpecified;
        }
        set {
            this.maximumValueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseRepititions {
    
    private int minimumValueField;
    
    private int maximumValueField;
    
    private bool maximumValueFieldSpecified;
    
    /// <remarks/>
    public int minimumValue {
        get {
            return this.minimumValueField;
        }
        set {
            this.minimumValueField = value;
        }
    }
    
    /// <remarks/>
    public int maximumValue {
        get {
            return this.maximumValueField;
        }
        set {
            this.maximumValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumValueSpecified {
        get {
            return this.maximumValueFieldSpecified;
        }
        set {
            this.maximumValueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseResistance {
    
    private int minimumValueField;
    
    private int maximumValueField;
    
    private bool maximumValueFieldSpecified;
    
    private string unitOfMeasurementField;
    
    /// <remarks/>
    public int minimumValue {
        get {
            return this.minimumValueField;
        }
        set {
            this.minimumValueField = value;
        }
    }
    
    /// <remarks/>
    public int maximumValue {
        get {
            return this.maximumValueField;
        }
        set {
            this.maximumValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumValueSpecified {
        get {
            return this.maximumValueFieldSpecified;
        }
        set {
            this.maximumValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string unitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseDistance {
    
    private int minimumValueField;
    
    private int maximumValueField;
    
    private bool maximumValueFieldSpecified;
    
    private string unitOfMeasurementField;
    
    /// <remarks/>
    public int minimumValue {
        get {
            return this.minimumValueField;
        }
        set {
            this.minimumValueField = value;
        }
    }
    
    /// <remarks/>
    public int maximumValue {
        get {
            return this.maximumValueField;
        }
        set {
            this.maximumValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumValueSpecified {
        get {
            return this.maximumValueFieldSpecified;
        }
        set {
            this.maximumValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string unitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseAdditionalDetails {
    
    private ExercisePlanExerciseGroupExerciseAdditionalDetailsDetail detailField;
    
    /// <remarks/>
    public ExercisePlanExerciseGroupExerciseAdditionalDetailsDetail detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ExercisePlanExerciseGroupExerciseAdditionalDetailsDetail {
    
    private string nameField;
    
    private int minimuValueField;
    
    private int maximuValueField;
    
    private bool maximuValueFieldSpecified;
    
    private string unitOfMeasurementField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public int minimuValue {
        get {
            return this.minimuValueField;
        }
        set {
            this.minimuValueField = value;
        }
    }
    
    /// <remarks/>
    public int maximuValue {
        get {
            return this.maximuValueField;
        }
        set {
            this.maximuValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximuValueSpecified {
        get {
            return this.maximuValueFieldSpecified;
        }
        set {
            this.maximuValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string unitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
}
