//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class Immunization {
    
    private System.DateTime dateAdministeredField;
    
    private bool dateAdministeredFieldSpecified;
    
    private string administeredByField;
    
    private ImmunizationVaccine vaccineField;
    
    private string sequenceField;
    
    private CodedValue anatomicSurfaceField;
    
    private string adverseEventField;
    
    /// <remarks/>
    public System.DateTime dateAdministered {
        get {
            return this.dateAdministeredField;
        }
        set {
            this.dateAdministeredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateAdministeredSpecified {
        get {
            return this.dateAdministeredFieldSpecified;
        }
        set {
            this.dateAdministeredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string administeredBy {
        get {
            return this.administeredByField;
        }
        set {
            this.administeredByField = value;
        }
    }
    
    /// <remarks/>
    public ImmunizationVaccine vaccine {
        get {
            return this.vaccineField;
        }
        set {
            this.vaccineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue anatomicSurface {
        get {
            return this.anatomicSurfaceField;
        }
        set {
            this.anatomicSurfaceField = value;
        }
    }
    
    /// <remarks/>
    public string adverseEvent {
        get {
            return this.adverseEventField;
        }
        set {
            this.adverseEventField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class ImmunizationVaccine {
    
    private CodedValue typeField;
    
    private string manufacturerField;
    
    private string lotField;
    
    private System.DateTime expirationField;
    
    private bool expirationFieldSpecified;
    
    /// <remarks/>
    public CodedValue type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string lot {
        get {
            return this.lotField;
        }
        set {
            this.lotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime expiration {
        get {
            return this.expirationField;
        }
        set {
            this.expirationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expirationSpecified {
        get {
            return this.expirationFieldSpecified;
        }
        set {
            this.expirationFieldSpecified = value;
        }
    }
}
