//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class Lab {
    
    private System.DateTime dateMeasuredField;
    
    private string labTypeField;
    
    private LabProvider laboratoryField;
    
    private LabPanel[] labPanelField;
    
    private LabTest[] labTestField;
    
    private string commentsField;
    
    /// <remarks/>
    public System.DateTime dateMeasured {
        get {
            return this.dateMeasuredField;
        }
        set {
            this.dateMeasuredField = value;
        }
    }
    
    /// <remarks/>
    public string labType {
        get {
            return this.labTypeField;
        }
        set {
            this.labTypeField = value;
        }
    }
    
    /// <remarks/>
    public LabProvider laboratory {
        get {
            return this.laboratoryField;
        }
        set {
            this.laboratoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("labPanel")]
    public LabPanel[] labPanel {
        get {
            return this.labPanelField;
        }
        set {
            this.labPanelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("labTest")]
    public LabTest[] labTest {
        get {
            return this.labTestField;
        }
        set {
            this.labTestField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class LabProvider {
    
    private string nameField;
    
    private string addressField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

public partial class Concentration : ValueOrRange {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MicroWithCultureLabTest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SingleResultLabTest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class LabTest {
    
    private System.DateTime dateMeasuredField;
    
    private CodedValue nameField;
    
    private bool finalField;
    
    /// <remarks/>
    public System.DateTime dateMeasured {
        get {
            return this.dateMeasuredField;
        }
        set {
            this.dateMeasuredField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool final {
        get {
            return this.finalField;
        }
        set {
            this.finalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class MicroWithCultureLabTest : LabTest {
    
    private CodedValue sourceField;
    
    private MicroWithCultureLabTestObservation[] observationField;
    
    private MicroWithCultureLabTestResult[] resultField;
    
    /// <remarks/>
    public CodedValue source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("observation")]
    public MicroWithCultureLabTestObservation[] observation {
        get {
            return this.observationField;
        }
        set {
            this.observationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("result")]
    public MicroWithCultureLabTestResult[] result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class MicroWithCultureLabTestObservation {
    
    private System.DateTime timeField;
    
    private Concentration microbialDensityField;
    
    private CodedValue organismField;
    
    private string extendedDescriptionField;
    
    private string cultureConditionField;
    
    private bool gramField;
    
    private bool gramFieldSpecified;
    
    private string morphologyField;
    
    private string organizationField;
    
    private string commentsField;
    
    private string isolateField;
    
    private string identityField;
    
    /// <remarks/>
    public System.DateTime time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public Concentration microbialDensity {
        get {
            return this.microbialDensityField;
        }
        set {
            this.microbialDensityField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue organism {
        get {
            return this.organismField;
        }
        set {
            this.organismField = value;
        }
    }
    
    /// <remarks/>
    public string extendedDescription {
        get {
            return this.extendedDescriptionField;
        }
        set {
            this.extendedDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string cultureCondition {
        get {
            return this.cultureConditionField;
        }
        set {
            this.cultureConditionField = value;
        }
    }
    
    /// <remarks/>
    public bool gram {
        get {
            return this.gramField;
        }
        set {
            this.gramField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gramSpecified {
        get {
            return this.gramFieldSpecified;
        }
        set {
            this.gramFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string morphology {
        get {
            return this.morphologyField;
        }
        set {
            this.morphologyField = value;
        }
    }
    
    /// <remarks/>
    public string organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isolate {
        get {
            return this.isolateField;
        }
        set {
            this.isolateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string identity {
        get {
            return this.identityField;
        }
        set {
            this.identityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class MicroWithCultureLabTestResult {
    
    private CodedValue organismField;
    
    private MicroWithCultureLabTestResultSensitivity[] sensitivityField;
    
    private string interpretationField;
    
    private string commentsField;
    
    private string isolateField;
    
    private string identityField;
    
    /// <remarks/>
    public CodedValue organism {
        get {
            return this.organismField;
        }
        set {
            this.organismField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sensitivity")]
    public MicroWithCultureLabTestResultSensitivity[] sensitivity {
        get {
            return this.sensitivityField;
        }
        set {
            this.sensitivityField = value;
        }
    }
    
    /// <remarks/>
    public string interpretation {
        get {
            return this.interpretationField;
        }
        set {
            this.interpretationField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isolate {
        get {
            return this.isolateField;
        }
        set {
            this.isolateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string identity {
        get {
            return this.identityField;
        }
        set {
            this.identityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class MicroWithCultureLabTestResultSensitivity {
    
    private CodedValue antibioticField;
    
    private Concentration mICField;
    
    private CodedValue interpretationField;
    
    private string commentsField;
    
    /// <remarks/>
    public CodedValue antibiotic {
        get {
            return this.antibioticField;
        }
        set {
            this.antibioticField = value;
        }
    }
    
    /// <remarks/>
    public Concentration MIC {
        get {
            return this.mICField;
        }
        set {
            this.mICField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue interpretation {
        get {
            return this.interpretationField;
        }
        set {
            this.interpretationField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class SingleResultLabTest : LabTest {
    
    private Result resultField;
    
    /// <remarks/>
    public Result result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class LabPanel {
    
    private CodedValue nameField;
    
    private LabTest[] labTestField;
    
    /// <remarks/>
    public CodedValue name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("labTest")]
    public LabTest[] labTest {
        get {
            return this.labTestField;
        }
        set {
            this.labTestField = value;
        }
    }
}
