//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class LabReport {
    
    private System.DateTime dateMeasuredField;
    
    private string labTypeField;
    
    private LabProvider laboratoryField;
    
    private string commentsField;
    
    private string firstPanelNameField;
    
    private string firstLabTestNameField;
    
    private string firstLabTestValueField;
    
    /// <remarks/>
    public System.DateTime dateMeasured {
        get {
            return this.dateMeasuredField;
        }
        set {
            this.dateMeasuredField = value;
        }
    }
    
    /// <remarks/>
    public string labType {
        get {
            return this.labTypeField;
        }
        set {
            this.labTypeField = value;
        }
    }
    
    /// <remarks/>
    public LabProvider laboratory {
        get {
            return this.laboratoryField;
        }
        set {
            this.laboratoryField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public string firstPanelName {
        get {
            return this.firstPanelNameField;
        }
        set {
            this.firstPanelNameField = value;
        }
    }
    
    /// <remarks/>
    public string firstLabTestName {
        get {
            return this.firstLabTestNameField;
        }
        set {
            this.firstLabTestNameField = value;
        }
    }
    
    /// <remarks/>
    public string firstLabTestValue {
        get {
            return this.firstLabTestValueField;
        }
        set {
            this.firstLabTestValueField = value;
        }
    }
}