//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class Medication {
    
    private System.DateTime dateStartedField;
    
    private bool dateStartedFieldSpecified;
    
    private System.DateTime dateStoppedField;
    
    private bool dateStoppedFieldSpecified;
    
    private string reasonStoppedField;
    
    private CodedValue nameField;
    
    private CodedValue brandNameField;
    
    private ValueAndUnit doseField;
    
    private CodedValue routeField;
    
    private ValueAndUnit strengthField;
    
    private CodedValue frequencyField;
    
    private Prescription prescriptionField;
    
    private string detailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dateStarted {
        get {
            return this.dateStartedField;
        }
        set {
            this.dateStartedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateStartedSpecified {
        get {
            return this.dateStartedFieldSpecified;
        }
        set {
            this.dateStartedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dateStopped {
        get {
            return this.dateStoppedField;
        }
        set {
            this.dateStoppedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateStoppedSpecified {
        get {
            return this.dateStoppedFieldSpecified;
        }
        set {
            this.dateStoppedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string reasonStopped {
        get {
            return this.reasonStoppedField;
        }
        set {
            this.reasonStoppedField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue brandName {
        get {
            return this.brandNameField;
        }
        set {
            this.brandNameField = value;
        }
    }
    
    /// <remarks/>
    public ValueAndUnit dose {
        get {
            return this.doseField;
        }
        set {
            this.doseField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue route {
        get {
            return this.routeField;
        }
        set {
            this.routeField = value;
        }
    }
    
    /// <remarks/>
    public ValueAndUnit strength {
        get {
            return this.strengthField;
        }
        set {
            this.strengthField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    public Prescription prescription {
        get {
            return this.prescriptionField;
        }
        set {
            this.prescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class Provider {
    
    private string nameField;
    
    private string institutionField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string institution {
        get {
            return this.institutionField;
        }
        set {
            this.institutionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class Prescription {
    
    private Provider byField;
    
    private System.DateTime onField;
    
    private bool onFieldSpecified;
    
    private System.DateTime stopOnField;
    
    private bool stopOnFieldSpecified;
    
    private bool dispenseAsWrittenField;
    
    private string durationField;
    
    private string refillInfoField;
    
    private string instructionsField;
    
    /// <remarks/>
    public Provider by {
        get {
            return this.byField;
        }
        set {
            this.byField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime on {
        get {
            return this.onField;
        }
        set {
            this.onField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onSpecified {
        get {
            return this.onFieldSpecified;
        }
        set {
            this.onFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime stopOn {
        get {
            return this.stopOnField;
        }
        set {
            this.stopOnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stopOnSpecified {
        get {
            return this.stopOnFieldSpecified;
        }
        set {
            this.stopOnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool dispenseAsWritten {
        get {
            return this.dispenseAsWrittenField;
        }
        set {
            this.dispenseAsWrittenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string refillInfo {
        get {
            return this.refillInfoField;
        }
        set {
            this.refillInfoField = value;
        }
    }
    
    /// <remarks/>
    public string instructions {
        get {
            return this.instructionsField;
        }
        set {
            this.instructionsField = value;
        }
    }
}