//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class SimpleClinicalNote {
    
    private System.DateTime dateOfVisitField;
    
    private System.DateTime finalizedAtField;
    
    private bool finalizedAtFieldSpecified;
    
    private CodedValue visitTypeField;
    
    private string visitLocationField;
    
    private CodedValue specialtyField;
    
    private Signature[] signatureField;
    
    private string chiefComplaintField;
    
    private string contentField;
    
    /// <remarks/>
    public System.DateTime dateOfVisit {
        get {
            return this.dateOfVisitField;
        }
        set {
            this.dateOfVisitField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime finalizedAt {
        get {
            return this.finalizedAtField;
        }
        set {
            this.finalizedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool finalizedAtSpecified {
        get {
            return this.finalizedAtFieldSpecified;
        }
        set {
            this.finalizedAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CodedValue visitType {
        get {
            return this.visitTypeField;
        }
        set {
            this.visitTypeField = value;
        }
    }
    
    /// <remarks/>
    public string visitLocation {
        get {
            return this.visitLocationField;
        }
        set {
            this.visitLocationField = value;
        }
    }
    
    /// <remarks/>
    public CodedValue specialty {
        get {
            return this.specialtyField;
        }
        set {
            this.specialtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature")]
    public Signature[] signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string chiefComplaint {
        get {
            return this.chiefComplaintField;
        }
        set {
            this.chiefComplaintField = value;
        }
    }
    
    /// <remarks/>
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://indivo.org/vocab/xml/documents#")]
public partial class Signature {
    
    private System.DateTime atField;
    
    private bool atFieldSpecified;
    
    private Provider providerField;
    
    /// <remarks/>
    public System.DateTime at {
        get {
            return this.atField;
        }
        set {
            this.atField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool atSpecified {
        get {
            return this.atFieldSpecified;
        }
        set {
            this.atFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Provider provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
}
