//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://indivo.org/vocab/xml/documents#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://indivo.org/vocab/xml/documents#", IsNullable=false)]
public partial class VitalSign {
    
	private CodedValue nameField;
	
	private string measuredByField;
	
    private System.DateTime dateMeasuredStartField;

    private System.DateTime dateMeasuredEndField;

    private ValueAndUnit resultField;
    
    private string siteField;
    
    private string positionField;
    
    private string techniqueField;
    
    private string commentsField;
    
    /// <remarks/>
    public CodedValue name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string measuredBy {
        get {
            return this.measuredByField;
        }
        set {
            this.measuredByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dateMeasuredStart {
        get {
            return this.dateMeasuredStartField;
        }
        set {
            this.dateMeasuredStartField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dateMeasuredEnd {
        get {
            return this.dateMeasuredEndField;
        }
        set {
            this.dateMeasuredEndField = value;
        }
    }
    
    /// <remarks/>
    public ValueAndUnit result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    public string site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public string technique {
        get {
            return this.techniqueField;
        }
        set {
            this.techniqueField = value;
        }
    }
    
    /// <remarks/>
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
}